### ISSUE TITLE
Player Name Colours

### ISSUE THREAD

**Issue by Parilia** [EclipseStudiosMC/tpa#1]
Sometimes when requesting a TPA player names can be displayed in black which in most situations is very hard to read.

**Comment by ElGeroIngles** [comment]
Got it, for next update the black color will be an option to turn on/off by an administrator, thanks for the suggestion! And also, as stayed in the description of the datapack, please report all bugs/suggestions in the [discord server](https://discord.gg/4pYjW9btNc), that's why I didn't noticed your suggestion before.
